name: "yolo_detector"
platform: "onnxruntime_onnx"
max_batch_size: 1
input [
  {
    name: "images"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 640, 640]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [-1, -1]
  }
]