{
 "title": "dashboard_TrafficAnalyzer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Загруженность дорог (машин в минуту)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT   \r\n  road_1 AS \"Road 1\",\r\n  road_2 AS \"Road 2\",\r\n  road_3 AS \"Road 3\",\r\n  road_4 AS \"Road 4\",\r\n  road_5 AS \"Road 5\"\r\nFROM traffic_info\r\nORDER BY timestamp DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "График изменения загруженности дорог",
   "type": "timeseries",
   "description": "число машин в минуту",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  road_1 AS \"Road 1\",\r\n  road_2 AS \"Road 2\",\r\n  road_3 AS \"Road 3\",\r\n  road_4 AS \"Road 4\",\r\n  road_5 AS \"Road 5\",\r\n  timestamp_date\r\nFROM\r\n  traffic_info\r\nORDER BY timestamp_date DESC\r\n\r\n"
    }
   ]
  },
  {
   "title": "Число машин на участке кругового движения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT timestamp_date, cars FROM traffic_info  "
    }
   ]
  }
 ]
}